dist: trusty
sudo: required
language: python
python:
  - '2.7'

branches:
  only:
    - master

git:
    # Handle git submodules yourself
    submodules: false

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
    - SALT_ARGS="-l debug --local --retcode-passthrough --pillar-root=$PWD/pillar --file-root=$PWD/state"

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -- stable

install:
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call --local grains.setval testing True
  - sudo salt-call --local grains.items

script:
  # For debugging purpose
  - sudo salt-call state.show_highstate $SALT_ARGS

  # Run highstate
  - sudo salt-call state.highstate $SALT_ARGS

  # Idempotence check
  - sudo salt-call state.highstate $SALT_ARGS > /tmp/second
  - cat /tmp/second
  - bash -c '! grep -q "^Not Run:" /tmp/second'
